parameters:
  # unique name of the job
  job_name: purge_azure_cdn
  # friendly name of the job
  display_name: Purge Azure CDN Enpoint
  # agent pool details (default: MSFT hosted Ubuntu)
  pool:
    vmImage: ubuntu-latest
  # additional arguments to add to execution
  azure_subscription: ''
  resource_group_name: ''
  endpoint_name: '' 
  profile_name: ''
  # node version
  node_version: '10.x'
  condition: { }
  variables_group: ''

jobs:
- deployment: ${{ parameters.job_name }}
  displayName: ${{ parameters.display_name }}
  condition: ${{ parameters.condition }}
  strategy:
    runOnce:
      deploy:
        steps:
        ##########################################
        ## Purge Azure CDN Endpoint CLI Command
        ##########################################
        - task: AzureCLI@2
          displayName: Purge Azure CDN Endpoint '$(endpoint_name)'
          inputs:
            azureSubscription: $(azure_subscription)
            scriptType: 'batch'
            scriptLocation: 'inlineScript'
            inlineScript: 'az cdn endpoint purge -g $(resource_group_name) -n $(endpoint_name) --profile-name $(profile_name) --content-paths ''/*'''