parameters:
  # unique name of the job
  job_name: deploy_sppkg
  # friendly name of the job
  display_name: Upload & deploy *.sppkg to SharePoint app catalog
  # agent pool details (default: MSFT hosted Ubuntu)
  pool:
    vmImage: ubuntu-latest
  # name of target enviroment deploying to
  target_environment: ''
  # additional arguments to add to execution of o365cli
  o365cli_spoAppAdd_extra_arguments: ''
  o365cli_spoAppDeploy_extra_arguments: ''
  # node version
  node_version: '10.x'
  condition: { }
  variables_group: ''

jobs:
- deployment: ${{ parameters.job_name }}
  displayName: ${{ parameters.display_name }}
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.target_environment }}
  condition: ${{ parameters.condition }}
  variables:
  - group: ${{ parameters.variables_group }}
  strategy:
    runOnce:
      deploy:
        steps:
        ##########################################
        ## specify which node version to use
        ##########################################
        - task: UseNode@1
          displayName: Set to Node.js ${{ parameters.node_version }}
          inputs:
            version: ${{ parameters.node_version }}
          condition: ne('${{ parameters.node_version }}', '')
        ##########################################
        ## install Office 365 CLI
        ##########################################
        - script: sudo npm install --global @pnp/office365-cli
          displayName: Install Office365 CLI
        ##########################################
        ## login to Office 365 CLI
        ##########################################
        - script: o365 login $(o365_app_catalog_site_url) --authType password --userName $(o365_user_login) --password $(o365_user_password)
          displayName: Login to Office365
        ##########################################
        ## download previously built *.sppkg
        ##########################################
        - task: DownloadPipelineArtifact@2
          displayName: Download SharePoint package (*.sppkg)
          inputs:
            buildType: current
            artifactName: spfx-package
        ##########################################
        ## determine name of generated *.sppkg
        ##########################################
        - script: |
            CMD_GET_SPPKG_NAME=$(find $(Pipeline.Workspace)/spfx-package -name '*.sppkg' -exec basename {} \;)
            echo "##vso[task.setvariable variable=SpPkgFileName;isOutput=true]${CMD_GET_SPPKG_NAME}"
          displayName: Get generated *.sppkg filename
          name: GetSharePointPackage
        ##########################################
        ## upload *.sppkg to the target app catalog
        ##########################################
        - script: o365 spo app add --filePath "$(Pipeline.Workspace)/spfx-package/$(GetSharePointPackage.SpPkgFileName)" --appCatalogUrl $(o365_app_catalog_site_url) --scope $(o365cli_app_catalog_scope) --overwrite ${{ parameters.o365cli_spoAppAdd_extra_arguments }}
          displayName: Upload SharePoint package to Site Collection App Catalog
        ##########################################
        ##
        ##########################################
        - script: o365 spo app deploy --name $(GetSharePointPackage.SpPkgFileName) --appCatalogUrl $(o365_app_catalog_site_url) --scope $(o365cli_app_catalog_scope) ${{ parameters.o365cli_spoAppDeploy_extra_arguments }}
          displayName: Deploy SharePoint package
