parameters:
  # unique name of the job
  job_name: versioning
  # friendly name of the job
  display_name: Set Versioning
  # agent pool details (default: MSFT hosted Ubuntu)
  pool:
    vmImage: ubuntu-latest
jobs:
- job: ${{ parameters.job_name }}
  displayName: ${{ parameters.display_name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: |
      npmVersionString=$(node -p "require('./package.json').version") 
      buildCounter=$[counter('${npmVersionString}', 0)]
      new_buildnumber=$npmVersionString.$buildCounter
      echo "##vso[task.setvariable variable=newBuildnumber;isOutput=true]${new_buildnumber}"
    displayName: 'set build number'
    name: setVersion
  - script: | 
      echo "##vso[build.updatebuildnumber]$(setVersion.newBuildnumber)"
    displayName: 'update build number'
    name: updateBuildNumber
