jobs:
  - job: Build_PowerShell_Win2016
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: |
          Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck
          .\PSWriteHTML.Tests.ps1
        displayName: "Run Pester Tests - PowerShell 5"
      #  - script: |
      #        pwsh -c '.\PSWriteHTML.Tests.ps1'
      #    displayName: "Run Pester Tests - PowerShell 6+"